### PR TITLE
29 upload raster take project

### PR DESCRIPTION
**Pull request by restaste**

### CODE REVIEW

**Comment by julienr** [comment]
LGTM. Just one thing naming-wise I wonder if we should call this `folder_id` in the python lib as well. That way we are consistent with the REST api docs.

(I have the feeling we'll rename projects into folders and folders into projects again in the future, but we wont break the API client library everytime :) )

**Comment by ao-picterra** [comment]
> LGTM. Just one thing naming-wise I wonder if we should call this `folder_id` in the python lib as well. That way we are consistent with the REST api docs.
> 
> I have the feeling we'll rename projects into folders and folders into projects again in the UI in the future, but we wont break the API client library everytime :)

Agree with J for the naming, then LGTM

**Comment by restaste** [comment]
Renamed `project_id` to `folder_id`.

**Review by julienr — APPROVED** [review]

**Comment by julienr** [comment]
Thanks !

**Pull request merged**
