### PR TITLE
[endpoint] Added new method to access the raster details

### LINKED ISSUE #73: Add a method to get details about a single raster
@RomainGratier this has no timeline, but a good way to start exploring a bit the public API when you have some bandwidth

### PR DESCRIPTION
**Pull request by RomainGratier**
### New method
A new method was added to get raster info from the API call https://app.picterra.ch/public/apidocs/v2/#tag/rasters/operation/getRasterById.

I also added an e2e test to ensure it works in a local environment.

fix #73

### CODE REVIEW

**Comment by ao-picterra** [comment]
one nitpick, LGTM, works perfect!

**Comment by RomainGratier** [comment]
> one nitpick, LGTM, works perfectly!

What is the nitpick?

**Comment by ao-picterra** [comment]
let's just remove test_e2e

**Comment by RomainGratier** [comment]
Done

**Review by ao-picterra — APPROVED** [review]

**Pull request merged**
